### ISSUE TITLE
Quillforms doesn't work with Astro when creating production build

### ISSUE THREAD

**Issue by stephen-wigginton** [quillforms/quillforms#118]
**Describe the bug**
when using `npm run build` to generate a production astro build, the following error is returned
```[commonjs--resolver] Unexpected character '!'
file: /Users/sparks/work/intro/community-web/node_modules/astro/astro.js:1:0
1: #!/usr/bin/env node
   ^
2: /* eslint-disable no-console */
3: 'use strict';
transforming (221) node_modules/email-validator/index.js error   Unexpected character '!'
  File:
    /Users/sparks/work/intro/community-web/node_modules/astro/astro.js
  Code:
    1: #!/usr/bin/env node
       ^
    2: /* eslint-disable no-console */
    3: 'use strict';
  Stacktrace:
RollupError: Unexpected character '!'
    at error (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:2125:30)
    at Module.error (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:13339:16)
    at Module.tryParse (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:14016:25)
    at Module.setSource (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:13626:39)
    at ModuleLoader.addModuleSource (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:23591:20)

  Cause:
SyntaxError: Unexpected character '!' (6:1)
    at Object.pp$4.raise (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:20995:13)
    at Object.pp.readToken_numberSign (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:22585:8)
    at Object.pp.getTokenFromCode (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:22660:17)
    at Object.pp.readToken (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:22350:15)
    at Object.readToken (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:24816:24)
    at Object.pp.nextToken (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:22341:15)
    at Object.pp.next (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:22302:8)
    at Object.pp$9.eat (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:18226:10)
    at Object.pp$9.semicolon (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:18273:13)
    at Object.parseImport (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:24964:12)
    at Object.pp$8.parseStatement (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:18472:49)
    at Object.pp$8.parseTopLevel (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:18353:21)
    at Object.parse (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:18125:15)
    at Function.parse (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:18175:35)
    at Graph.contextParse (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:24622:38)
    at Module.tryParse (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:14013:31)
    at Module.setSource (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:13626:39)
    at ModuleLoader.addModuleSource (file:///Users/sparks/work/intro/community-web/node_modules/rollup/dist/es/shared/node-entry.js:23591:20)
    ```
**To Reproduce**
1. `npm create astro@latest`
2.` npx astro add react`
3. `npm install @quillforms/renderer-core --save`
4. `npm install @quillforms/react-renderer-utils --save`
5. create update index.astro to have a basic form
6. `npm run build`
above error pops up

**Expected behavior**
A clear and concise description of what you expectedstephen to happen.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: OSX
 - Browser N/A
 - Version v4.2.0 of quillforms-latest. 2.1.3 of astro to latest

**Additional context**

**Comment by mdmag** [comment]
Closing due to no activity
