### ISSUE TITLE
Hello Guys, any help?

### ISSUE THREAD

**Issue by mgip** [quillforms/quillforms#135]
Cannot read properties of undefined (reading 'quotationMarks')
TypeError: Cannot read properties of undefined (reading 'quotationMarks')
    at CounterIconComponent (http://localhost:3001/static/js/bundle.js:54348:35)
    at renderWithHooks (http://localhost:3001/static/js/bundle.js:134559:22)
    at mountIndeterminateComponent (http://localhost:3001/static/js/bundle.js:137845:17)
    at beginWork (http://localhost:3001/static/js/bundle.js:139141:20)
    at HTMLUnknownElement.callCallback (http://localhost:3001/static/js/bundle.js:124151:18)
    at Object.invokeGuardedCallbackDev (http://localhost:3001/static/js/bundle.js:124195:20)
    at invokeGuardedCallback (http://localhost:3001/static/js/bundle.js:124252:35)
    at beginWork$1 (http://localhost:3001/static/js/bundle.js:144126:11)
    at performUnitOfWork (http://localhost:3001/static/js/bundle.js:143373:16)
    at workLoopSync (http://localhost:3001/static/js/bundle.js:143296:9)

**Comment by mdmag** [comment]
Can you just copy paste the formObj prop here?

**Comment by mdmag** [comment]
Closing due to no response

**Comment by aligg73** [comment]
Hi,

I am encountering the same issue.
The form opens up normally when I am logged into Wordpress, but a non-logged in user gets to see an endless spinner.

console is showing this (and more):
```
Uncaught TypeError: Cannot read properties of undefined (reading '__dangerousOptInToUnstableAPIsOnlyForCoreModules')
    at data.min.js:2:10321
    at data.min.js:9:4305
    at data.min.js:9:4342
gen-ai-use-case-survey/?quillforms-shortcode=1&quillforms-redirection=top:169 Uncaught TypeError: Cannot read properties of undefined (reading 'use')
    at gen-ai-use-case-survey/?quillforms-shortcode=1&quillforms-redirection=top:169:3
    at gen-ai-use-case-survey/?quillforms-shortcode=1&quillforms-redirection=top:170:4
index.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'createReduxStore')
    at index.js:1:1570
    at index.js:1:7257
```

I am using Chrome on Linux.

How can i obtain the formObj prop and paste it here?

Thanks.
